### PR TITLE
Adunits and Timeline Sections - Added bidderRequests and topics to JSON modals

### PR DESCRIPTION
**Pull request by jlquaccia**
ADUNITS section
- added bidderRequests to the JSON modal popup when a user clicks on a bid under the "bidders" column.
- also added topics present in a user's browser for a specific url (if any are present), when a user clicks on a bid under the "bidders" column.  if none are present topics will be sent as an empty array.

TIMELINE section
- added topics within the json modal popup when a user clicks on an ssp in the timeline section as well (bidderRequests are present here as well, they were there prior to this PR)

### CODE REVIEW

**Review by florianerl — APPROVED** [review]
lgtm

**Comment by jlquaccia** [comment]
thanks @florianerl !

**Comment by florianerl** [comment]
Hi @jlquaccia , 

very welcome 😃 ! 
I'll do some beta testing with this version and plan to release it beginning of next week.

**Comment by jlquaccia** [comment]
@florianerl awesome, I see that has been released!  thank you!

**Pull request merged**
