### PR TITLE
Proposal - Ad Mask Overlay Style Tweaks

### PR DESCRIPTION
**Pull request by timothyasp**
Huge fan of the new extension - it's a huge improvement over prior work.  Thanks for your work on this 🙏   

I've been really loving the overlay feature, but I was having trouble reading the content in the overlay because of the low contrast between the orange and the MUI default text color.

Also there was some bugs where the padding with no `border-box` was making the overlay go outside the ad unit, and where the zindex was sometimes not "high" enough, so I made it max int.

I made some changes that I think improves usability and readability, but is still in the same style as what's currently live.  Let me know what you think

Before
Screen Shot on 2022-05-18 at 18-44-38

After
Screen Shot on 2022-05-18 at 18-43-26

### CODE REVIEW

**Comment by florianerl** [comment]
Hi @timothyasp, 

thanks for your feedback and contribution. I was working on another (yet similar) issue [affecting the overlays](https://github.com/prebid/professor-prebid/issues/6). I pushed an initial version to this branch: https://github.com/prebid/professor-prebid/tree/6-ad-gam-query-id-to-the-overlay
and would be highly interested in your feedback and the results on your page. I added a minimize-, maximize-, close- and reload button along with some extra info coming from google admanager: 

image

image

image

Regarding your PR: I tried to remove all SASS/SCSS/CSS related dependencies in favour of [mui's sx prop](https://mui.com/system/basics/#:~:text=design%20with%20constraints.-,The,prop,-The) and would prefer to keep it that way for code consistency and compatibility reasons.

**Comment by timothyasp** [comment]
Looks MUCH better! I'll check that out locally and send over some feedback. 

Closing this pull

**Comment by timothyasp** [comment]
@florianerl One minor thing

Adding `box-sizing: border-box` to the overlay fixes the padding overflow on the overlays. 

https://d.pr/i/q2PBA3 in AdOverlayComponent.tsx

**Comment by timothyasp** [comment]
Also, i'm not seeing any of the addition GAM details.  Is there some config that's needed for those fields to show (like shown here) 
image
?  I'm fetched up to your most recent pushes

**Comment by timothyasp** [comment]
Ah-ha - found the bug.

My prebid is set up where we specify the `div` where that'll contain the ad unit, so the code on GamDetailsComponent.tsx @ line 23

```
      const slot = slots.find((slot) => slot.getSlotElementId() === elementId);
```

would fail since slotElementId is just the divId, and not the full path which is the elementId

Changing that line to 

```
      const slot = slots.find((slot) => slot.getAdUnitPath() === elementId);
```

fixes it for me.

**Comment by florianerl** [comment]
> Ah-ha - found the bug.
> 
> My prebid is set up where we specify the `div` where that'll contain the ad unit, so the code on GamDetailsComponent.tsx @ line 23
> 
> ```
>       const slot = slots.find((slot) => slot.getSlotElementId() === elementId);
> ```
> 
> would fail since slotElementId is just the divId, and not the full path which is the elementId
> 
> Changing that line to
> 
> ```
>       const slot = slots.find((slot) => slot.getAdUnitPath() === elementId);
> ```
> 
> fixes it for me.

 thanks @timothyasp . I'll check that on monday (tuesday the latest). Same for your PR.

**Comment by florianerl** [comment]
hi @timothyasp ,


could you please shed some more light on this setup? Why do you use the AdUnitPath as elementId? Can you share a website url with this setup? 
```
const slot = slots.find((slot) => slot.getAdUnitPath() === elementId);
```
breaks the matching on most of the pages i test while working on the extension, like www.heise.de or www.cnn.com or www.brightsideme.com or www.dailymail.co.uk or www.accuweather.com 

i guess we could safely add it as a fallback like
```
      const slot = slots.find((slot) => slot.getSlotElementId() === elementId) || slots.find((slot) => slot.getAdUnitPath() === elementId);
```
@allanjun  what do you think?

**Comment by timothyasp** [comment]
Yea the fallback is the right solution.  It's a very standard prebid setup - I don't have a public URL, but this is the defineSlot

```
window.globalAds.push(googletag.defineSlot(adUnit.code, adUnit.mediaTypes.banner.sizes, adUnit.divId).addService(googletag.pubads()));
```

**Pull request closed without merging**
